const errorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_EXISTS: 'USER_EXISTS',
  FORBIDDEN: 'FORBIDDEN',

  UNKNOWN: 'UNKNOWN',
};

module.exports = errorCodes;
